*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 26.12.2019 at 13:07:45
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZJPVTJPBPVLDRLTY................................*
FORM GET_DATA_ZJPVTJPBPVLDRLTY.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZTJPBPVALIDRLTYP WHERE
(VIM_WHERETAB) .
    CLEAR ZJPVTJPBPVLDRLTY .
ZJPVTJPBPVLDRLTY-CLIENT =
ZTJPBPVALIDRLTYP-CLIENT .
ZJPVTJPBPVLDRLTY-ASSI_TYP =
ZTJPBPVALIDRLTYP-ASSI_TYP .
ZJPVTJPBPVLDRLTY-APPL =
ZTJPBPVALIDRLTYP-APPL .
ZJPVTJPBPVLDRLTY-RLTYP =
ZTJPBPVALIDRLTYP-RLTYP .
ZJPVTJPBPVLDRLTY-CARDI =
ZTJPBPVALIDRLTYP-CARDI .
ZJPVTJPBPVLDRLTY-OBLI =
ZTJPBPVALIDRLTYP-OBLI .
ZJPVTJPBPVLDRLTY-BU_GROUP =
ZTJPBPVALIDRLTYP-BU_GROUP .
    SELECT SINGLE * FROM TB001 WHERE
BU_GROUP = ZTJPBPVALIDRLTYP-BU_GROUP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TB002 WHERE
BU_GROUP = TB001-BU_GROUP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZJPVTJPBPVLDRLTY-TXT15 =
TB002-TXT15 .
      ENDIF.
    ENDIF.
    SELECT SINGLE * FROM TB003 WHERE
ROLE = ZTJPBPVALIDRLTYP-RLTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TB003T WHERE
ROLE = TB003-ROLE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZJPVTJPBPVLDRLTY-RLTITL =
TB003T-RLTITL .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZJPVTJPBPVLDRLTY.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZJPVTJPBPVLDRLTY .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZJPVTJPBPVLDRLTY.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZJPVTJPBPVLDRLTY-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZTJPBPVALIDRLTYP WHERE
  ASSI_TYP = ZJPVTJPBPVLDRLTY-ASSI_TYP AND
  APPL = ZJPVTJPBPVLDRLTY-APPL AND
  RLTYP = ZJPVTJPBPVLDRLTY-RLTYP .
    IF SY-SUBRC = 0.
    DELETE ZTJPBPVALIDRLTYP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZTJPBPVALIDRLTYP WHERE
  ASSI_TYP = ZJPVTJPBPVLDRLTY-ASSI_TYP AND
  APPL = ZJPVTJPBPVLDRLTY-APPL AND
  RLTYP = ZJPVTJPBPVLDRLTY-RLTYP .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZTJPBPVALIDRLTYP.
    ENDIF.
ZTJPBPVALIDRLTYP-CLIENT =
ZJPVTJPBPVLDRLTY-CLIENT .
ZTJPBPVALIDRLTYP-ASSI_TYP =
ZJPVTJPBPVLDRLTY-ASSI_TYP .
ZTJPBPVALIDRLTYP-APPL =
ZJPVTJPBPVLDRLTY-APPL .
ZTJPBPVALIDRLTYP-RLTYP =
ZJPVTJPBPVLDRLTY-RLTYP .
ZTJPBPVALIDRLTYP-CARDI =
ZJPVTJPBPVLDRLTY-CARDI .
ZTJPBPVALIDRLTYP-OBLI =
ZJPVTJPBPVLDRLTY-OBLI .
ZTJPBPVALIDRLTYP-BU_GROUP =
ZJPVTJPBPVLDRLTY-BU_GROUP .
    IF SY-SUBRC = 0.
    UPDATE ZTJPBPVALIDRLTYP ##WARN_OK.
    ELSE.
    INSERT ZTJPBPVALIDRLTYP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZJPVTJPBPVLDRLTY-UPD_FLAG,
STATUS_ZJPVTJPBPVLDRLTY-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZJPVTJPBPVLDRLTY.
  SELECT SINGLE * FROM ZTJPBPVALIDRLTYP WHERE
ASSI_TYP = ZJPVTJPBPVLDRLTY-ASSI_TYP AND
APPL = ZJPVTJPBPVLDRLTY-APPL AND
RLTYP = ZJPVTJPBPVLDRLTY-RLTYP .
ZJPVTJPBPVLDRLTY-CLIENT =
ZTJPBPVALIDRLTYP-CLIENT .
ZJPVTJPBPVLDRLTY-ASSI_TYP =
ZTJPBPVALIDRLTYP-ASSI_TYP .
ZJPVTJPBPVLDRLTY-APPL =
ZTJPBPVALIDRLTYP-APPL .
ZJPVTJPBPVLDRLTY-RLTYP =
ZTJPBPVALIDRLTYP-RLTYP .
ZJPVTJPBPVLDRLTY-CARDI =
ZTJPBPVALIDRLTYP-CARDI .
ZJPVTJPBPVLDRLTY-OBLI =
ZTJPBPVALIDRLTYP-OBLI .
ZJPVTJPBPVLDRLTY-BU_GROUP =
ZTJPBPVALIDRLTYP-BU_GROUP .
    SELECT SINGLE * FROM TB001 WHERE
BU_GROUP = ZTJPBPVALIDRLTYP-BU_GROUP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TB002 WHERE
BU_GROUP = TB001-BU_GROUP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZJPVTJPBPVLDRLTY-TXT15 =
TB002-TXT15 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZJPVTJPBPVLDRLTY-TXT15 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZJPVTJPBPVLDRLTY-TXT15 .
    ENDIF.
    SELECT SINGLE * FROM TB003 WHERE
ROLE = ZTJPBPVALIDRLTYP-RLTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TB003T WHERE
ROLE = TB003-ROLE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZJPVTJPBPVLDRLTY-RLTITL =
TB003T-RLTITL .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZJPVTJPBPVLDRLTY-RLTITL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZJPVTJPBPVLDRLTY-RLTITL .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZJPVTJPBPVLDRLTY USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZJPVTJPBPVLDRLTY-ASSI_TYP TO
ZTJPBPVALIDRLTYP-ASSI_TYP .
MOVE ZJPVTJPBPVLDRLTY-APPL TO
ZTJPBPVALIDRLTYP-APPL .
MOVE ZJPVTJPBPVLDRLTY-RLTYP TO
ZTJPBPVALIDRLTYP-RLTYP .
MOVE ZJPVTJPBPVLDRLTY-CLIENT TO
ZTJPBPVALIDRLTYP-CLIENT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZTJPBPVALIDRLTYP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZTJPBPVALIDRLTYP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZTJPBPVALIDRLTYP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZJPVTJPBPVLDRLTY USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZTJPBPVALIDRLTYP-CLIENT =
ZJPVTJPBPVLDRLTY-CLIENT .
ZTJPBPVALIDRLTYP-ASSI_TYP =
ZJPVTJPBPVLDRLTY-ASSI_TYP .
ZTJPBPVALIDRLTYP-APPL =
ZJPVTJPBPVLDRLTY-APPL .
ZTJPBPVALIDRLTYP-RLTYP =
ZJPVTJPBPVLDRLTY-RLTYP .
ZTJPBPVALIDRLTYP-CARDI =
ZJPVTJPBPVLDRLTY-CARDI .
ZTJPBPVALIDRLTYP-OBLI =
ZJPVTJPBPVLDRLTY-OBLI .
ZTJPBPVALIDRLTYP-BU_GROUP =
ZJPVTJPBPVLDRLTY-BU_GROUP .
    SELECT SINGLE * FROM TB001 WHERE
BU_GROUP = ZTJPBPVALIDRLTYP-BU_GROUP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TB002 WHERE
BU_GROUP = TB001-BU_GROUP AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZJPVTJPBPVLDRLTY-TXT15 =
TB002-TXT15 .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZJPVTJPBPVLDRLTY-TXT15 .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZJPVTJPBPVLDRLTY-TXT15 .
    ENDIF.
    SELECT SINGLE * FROM TB003 WHERE
ROLE = ZTJPBPVALIDRLTYP-RLTYP .
    IF SY-SUBRC EQ 0.
      SELECT SINGLE * FROM TB003T WHERE
ROLE = TB003-ROLE AND
SPRAS = SY-LANGU .
      IF SY-SUBRC EQ 0.
ZJPVTJPBPVLDRLTY-RLTITL =
TB003T-RLTITL .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZJPVTJPBPVLDRLTY-RLTITL .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZJPVTJPBPVLDRLTY-RLTITL .
    ENDIF.
ENDFORM.
